apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    "port-forward-controller.atte.cloud/enable": "true"
spec:
  containers:
  - name: container
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 8080
